FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/

COPY target/*-runner /work/application
COPY src/main/docker/config/application.properties /work/config/application.properties

RUN chmod -R 775 /work
EXPOSE 8080
CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]